SELECT t.*
,t1.DIDSTD,t1.DNAME
FROM 
(
SELECT s.HOSPCODE,s.PID,s.SEQ,s.DATE_SERV,s.CHIEFCOMP
,GROUP_CONCAT(x.DIAGCODE ORDER BY x.diagtype SEPARATOR ',') as DIAGCODE
,GROUP_CONCAT(x.DIAGTYPE ORDER BY x.diagtype SEPARATOR ',') as DIAGTYPE
FROM service s
LEFT JOIN diagnosis_opd x
ON s.HOSPCODE=x.HOSPCODE AND s.PID=x.PID AND s.SEQ=x.SEQ 
WHERE s.HOSPCODE='07733'
-- AND s.DATE_SERV BETWEEN '2016-09-01' AND '2016-09-30'
GROUP BY s.HOSPCODE,s.PID,s.SEQ
) as t
LEFT JOIN	 drug_opd t1
ON t.HOSPCODE=t1.HOSPCODE AND t.PID=t1.PID AND t.SEQ=t1.SEQ
ORDER BY t.DATE_SERV DESC 
