SELECT p.HOSPCODE,p.PID,p.CID,p.BIRTH
,e.VACCINETYPE,e.DATE_SERV,e.VACCINEPLACE
-- ,TIMESTAMPDIFF(week,p.BIRTH,e.DATE_SERV)  as INTERVALS
,TIMESTAMPDIFF(DAY,p.BIRTH,e.DATE_SERV)  as INTERVALS

FROM person p
INNER JOIN epi e
ON p.HOSPCODE=e.HOSPCODE AND p.PID=e.PID 
WHERE e.VACCINETYPE='091' 
HAVING INTERVALS <  28
ORDER BY DATE_SERV DESC ;
