SELECT t.*
,SUBSTRING_INDEX(GA,',',1)   as X
,SUBSTRING_INDEX(STR_EDC,',',1)   as Y
FROM 
(
SELECT p.HOSPCODE,p.CID,p.`NAME`,p.LNAME,p.TYPEAREA,p.NATION
,GROUP_CONCAT(a.DATE_SERV ORDER BY a.DATE_SERV SEPARATOR ',') as VISIT_ANC
,GROUP_CONCAT(a.GA ORDER BY a.DATE_SERV SEPARATOR ',') as GA
,GROUP_CONCAT(n.LMP ORDER BY n.LMP SEPARATOR ',') as STR_LMP
,GROUP_CONCAT(n.EDC ORDER BY n.EDC DESC SEPARATOR ',') as STR_EDC
FROM person p 
LEFT JOIN anc a 
ON a.HOSPCODE=p.HOSPCODE AND a.PID=p.PID
LEFT JOIN prenatal n
ON n.HOSPCODE=p.HOSPCODE AND n.PID=p.PID
WHERE  a.DATE_SERV > '2016-09-30'
AND a.GA > 15
AND NOT ISNULL(p.CID)
AND p.NATION='099'
GROUP BY p.CID 
) as t
HAVING  X BETWEEN 16 AND 39  
ORDER BY X 
