SELECT p.HOSPCODE,p.PID,p.CID,p.NAME,p.LNAME,p.TYPEAREA,p.DISCHARGE
,GROUP_CONCAT(c.CHRONIC  ORDER BY c.DATE_DIAG DESC  SEPARATOR ',' )  AS DIAGCODE
,GROUP_CONCAT(c.TYPEDISCH  ORDER BY c.DATE_DIAG DESC  SEPARATOR ',' )  AS TYPEDISCH

FROM chronic c
LEFT JOIN person p
ON c.HOSPCODE=p.HOSPCODE AND c.PID=p.PID 
WHERE p.TYPEAREA IN('1','3')
AND p.DISCHARGE='9'
-- AND substr(c.CHRONIC,1,3)  BETWEEN 'E10' AND 'E14' 
AND substr(c.CHRONIC,1,3)  BETWEEN 'I10' AND 'I15'
GROUP BY p.CID 
HAVING substr(TYPEDISCH,1,2)<>'03' 
