SELECT t.HOSPCODE,t.PID,t.CID,t.`NAME`,t.LNAME,t.BIRTH,AGE_DAY
,if(AGE_DAY >1 AND NOT ISNULL(t.BCG),'1',IF(AGE_DAY >1 AND ISNULL(t.BCG) ,'0','9')) as BCG
,if(AGE_DAY >1 AND NOT ISNULL(t.HBV1),'1',IF(AGE_DAY >1 AND ISNULL(t.HBV1) ,'0','9')) as HBV1
,if(AGE_DAY >56 AND NOT ISNULL(t.DHB1),'1',IF(AGE_DAY >56 AND ISNULL(t.DHB1) ,'0','9')) as DHB1
,if(AGE_DAY >56 AND NOT ISNULL(t.OPV1),'1',IF(AGE_DAY >56 AND ISNULL(t.OPV1) ,'0','9')) as OPV1
,if(AGE_DAY >56 AND NOT ISNULL(t.R21),'1',IF(AGE_DAY >56 AND ISNULL(t.R21) ,'0','9')) as R21
,if(AGE_DAY >112 AND NOT ISNULL(t.DHB2),'1',IF(AGE_DAY >112 AND ISNULL(t.DHB2) ,'0','9')) as DHB2
,if(AGE_DAY >112 AND NOT ISNULL(t.OPV2),'1',IF(AGE_DAY >112 AND ISNULL(t.OPV2) ,'0','9')) as OPV2
,if(AGE_DAY >112 AND NOT ISNULL(t.R22),'1',IF(AGE_DAY >112 AND ISNULL(t.R22),'0','9')) as R22
,if(AGE_DAY >112 AND NOT ISNULL(t.IPV),'1',IF(AGE_DAY >112 AND ISNULL(t.IPV) ,'0','9')) as IPV
,if(AGE_DAY >168 AND NOT ISNULL(t.DHB3),'1',IF(AGE_DAY >168 AND ISNULL(t.DHB3) ,'0','9')) as DHB3
,if(AGE_DAY >168 AND NOT ISNULL(t.OPV3),'1',IF(AGE_DAY >168 AND ISNULL(t.OPV3) ,'0','9')) as OPV3
,if(AGE_DAY >168 AND NOT ISNULL(t.R23),'1',IF(AGE_DAY >168 AND ISNULL(t.R23) ,'0','9')) as R23
,if(AGE_DAY >224 AND NOT ISNULL(t.MMR1),'1',IF(AGE_DAY >252 AND ISNULL(t.MMR1) ,'0','9')) as MMR1
,if(AGE_DAY >504 AND NOT ISNULL(t.DTP4),'1',IF(AGE_DAY >504 AND ISNULL(t.DTP4) ,'0','9')) as DTP4
,if(AGE_DAY >504 AND NOT ISNULL(t.OPV4),'1',IF(AGE_DAY >504 AND ISNULL(t.OPV4) ,'0','9')) as OPV4
,if(AGE_DAY >365 AND NOT ISNULL(t.LAJE1),'1',IF(AGE_DAY >365 AND ISNULL(t.LAJE1) ,'0','9')) as LAJE1
,if(AGE_DAY >532 AND NOT ISNULL(t.LAJE2),'1',IF(AGE_DAY >532 AND ISNULL(t.LAJE2) ,'0','9')) as LAJE2
,if(AGE_DAY >840 AND NOT ISNULL(t.MMR2),'1',IF(AGE_DAY >840 AND ISNULL(t.MMR2) ,'0','9')) as MMR2
,if(AGE_DAY >1680 AND NOT ISNULL(t.DTP5),'1',IF(AGE_DAY >1680 AND ISNULL(t.DTP5) ,'0','9')) as DTP5
,if(AGE_DAY >1680 AND NOT ISNULL(t.OPV5),'1',IF(AGE_DAY >1680 AND ISNULL(t.OPV5) ,'0','9')) as OPV5  
FROM (
SELECT p.HOSPCODE,p.PID,p.CID,p.`NAME`,p.LNAME,p.BIRTH,p.DISCHARGE,p.TYPEAREA 
,TIMESTAMPDIFF(MONTH,p.birth,CURDATE()) as AGE_MO
,TIMESTAMPDIFF(DAY,p.birth,CURDATE()) as AGE_DAY
,MIN(IF(e.VACCINETYPE='010',e.DATE_SERV,NULL)) AS BCG
,MIN(IF(e.VACCINETYPE='041',e.DATE_SERV,NULL)) AS HBV1
,MIN(IF(e.VACCINETYPE='091',e.DATE_SERV,NULL)) AS DHB1
,MIN(IF(e.VACCINETYPE='081',e.DATE_SERV,NULL)) AS OPV1
,MIN(IF(e.VACCINETYPE='R21',e.DATE_SERV,NULL)) AS R21
,MIN(IF(e.VACCINETYPE='092',e.DATE_SERV,NULL)) AS DHB2
,MIN(IF(e.VACCINETYPE='082',e.DATE_SERV,NULL)) AS OPV2
,MIN(IF(e.VACCINETYPE='R22',e.DATE_SERV,NULL)) AS R22
,MIN(IF(e.VACCINETYPE='IPV-P',e.DATE_SERV,NULL)) AS IPV
,MIN(IF(e.VACCINETYPE='093',e.DATE_SERV,NULL)) AS DHB3
,MIN(IF(e.VACCINETYPE='083',e.DATE_SERV,NULL)) AS OPV3
,MIN(IF(e.VACCINETYPE='R23',e.DATE_SERV,NULL)) AS R23
,MIN(IF(e.VACCINETYPE='061',e.DATE_SERV,NULL)) AS MMR1
,MIN(IF(e.VACCINETYPE='073',e.DATE_SERV,NULL)) AS MMR2
,MIN(IF(e.VACCINETYPE='034',e.DATE_SERV,NULL)) AS DTP4
,MIN(IF(e.VACCINETYPE='084',e.DATE_SERV,NULL)) AS OPV4
,MIN(IF(e.VACCINETYPE='035',e.DATE_SERV,NULL)) AS DTP5
,MIN(IF(e.VACCINETYPE='085',e.DATE_SERV,NULL)) AS OPV5
,MIN(IF(e.VACCINETYPE='J11',e.DATE_SERV,NULL)) AS LAJE1
,MIN(IF(e.VACCINETYPE='J12',e.DATE_SERV,NULL)) AS LAJE2
,MIN(IF(e.VACCINETYPE='051',e.DATE_SERV,NULL)) AS JE1
,MIN(IF(e.VACCINETYPE='052',e.DATE_SERV,NULL)) AS JE2
,MIN(IF(e.VACCINETYPE='053',e.DATE_SERV,NULL)) AS JE3
,MIN(IF(e.VACCINETYPE='R11',e.DATE_SERV,NULL)) AS R11
,MIN(IF(e.VACCINETYPE='R12',e.DATE_SERV,NULL)) AS R12
FROM person p
LEFT JOIN epi e
ON p.HOSPCODE=e.HOSPCODE AND p.pid =e.pid 
WHERE p.HOSPCODE='07714'
AND p.TYPEAREA in('1','3')
AND p.DISCHARGE='9'
AND p.BIRTH BETWEEN '2015-10-01' and	 '2016-09-30'
GROUP BY p.CID
) as t 
HAVING BCG='0' OR HBV1='0' OR DHB1='0' AND OPV1='0' AND R21='0'  OR DHB2='0' AND OPV2='0' AND R22='0'  OR DHB3='0' AND OPV3='0' AND R23='0'  OR MMR1='0' 
ORDER BY t.HOSPCODE,t.BIRTH 

