SELECT  t.HOSPCODE,t.CID,t.`NAME`,t.LNAME,t.BIRTH,t.DISCHARGE,t.TYPEAREA
,t.DHB1,t.DHB2,t.DHB3
,DATEDIFF(t.DHB2,t.DHB1) AS INTERVAL1 
,DATEDIFF(t.DHB3,t.DHB2) AS INTERVAL2 
FROM (
SELECT p.HOSPCODE,p.CID,p.`NAME`,p.LNAME,p.BIRTH,p.DISCHARGE,p.TYPEAREA 
,MIN(IF(e.VACCINETYPE='091',e.DATE_SERV,NULL)) AS DHB1
,MIN(IF(e.VACCINETYPE='092',e.DATE_SERV,NULL)) AS DHB2
,MIN(IF(e.VACCINETYPE='093',e.DATE_SERV,NULL)) AS DHB3
FROM person p
LEFT JOIN epi e
ON p.HOSPCODE=e.HOSPCODE AND p.pid =e.pid 
WHERE	 p.HOSPCODE<>'10727'
GROUP BY p.CID
HAVING NOT ISNULL(DHB1) AND NOT ISNULL(DHB2) AND NOT ISNULL(DHB3)
) as t 
HAVING INTERVAL1 < 28 OR INTERVAL2 < 28;
