DROP TABLE IF EXISTS me_need_flu;
CREATE TABLE me_need_flu (
    HOSPCODE VARCHAR(5),
	PID VARCHAR(15),
	CID VARCHAR(13),
	BIRTH date,
	AGE int ,
	TYPEAREA VARCHAR(1),
	DISCHARGE VARCHAR(1),
	GRP0 int(11),
	GRP1 int(11),
	GRP2 int(11),
	GRP3 int(11),
	GRP4 int(11),
	GRP5 int(11),
	GRP6 int(11),
	GRP7 int(11),
	GRP8 int(11),
	GRP9 int(11),
	GRP10 int(11),
	GRP11 int(11),
	GRP12 int(11),
	
	C01 VARCHAR(100),
	C02 VARCHAR(100),
	C03 VARCHAR(100),
	C04 VARCHAR(100),
	C05 VARCHAR(100),
	C06 VARCHAR(100),
	C07 VARCHAR(100),
	C08 VARCHAR(100),
	C09 VARCHAR(100),
	C10 VARCHAR(100),
	INDEX USING BTREE (CID),
    PRIMARY KEY (HOSPCODE,PID)
) ENGINE=InnoDB;

# add person

INSERT INTO me_need_flu (HOSPCODE,PID,CID,BIRTH,TYPEAREA,DISCHARGE  )
SELECT HOSPCODE,PID,CID,BIRTH,TYPEAREA,DISCHARGE 
FROM person 
WHERE NOT ISNULL(CID) AND CID <>'' AND SUBSTR(CID,1,1)<>'0' AND SUBSTR(CID,1,1)<>'7' AND SUBSTR(CID,1,1)<>'8' AND SUBSTR(CID,1,1)<>'9';


# 0 AGING

UPDATE me_need_flu a 
JOIN 
(
SELECT HOSPCODE,PID,CID,BIRTH
,TIMESTAMPDIFF(YEAR,BIRTH,'2017-06-01') as AGE
FROM person 
WHERE DISCHARGE='9'
HAVING AGE BETWEEN 65 AND 150 
) b 
ON a.CID = b.CID  
SET a.GRP0 = '1';


# 1 COPD J41-J44 

UPDATE me_need_flu a 
JOIN 
(
SELECT p.CID 
FROM diagnosis_opd o
LEFT JOIN person p
ON o.HOSPCODE=p.HOSPCODE and	 o.PID=p.PID 
WHERE substr(DIAGCODE,1,3) BETWEEN 'J41' AND 'J44' 
) b 
ON a.CID = b.CID  
SET a.GRP1 = '1';


# 2 Asthma J45-J46

UPDATE me_need_flu a 
JOIN 
(
SELECT p.CID 
FROM diagnosis_opd o
LEFT JOIN person p
ON o.HOSPCODE=p.HOSPCODE and	 o.PID=p.PID 
WHERE substr(DIAGCODE,1,3) BETWEEN 'J45' AND 'J46' 
) b 
ON a.CID = b.CID  
SET a.GRP2 = '1';

# 3 Heart Disease I05-I09 I11  I13  I20  I52  

UPDATE me_need_flu a 
JOIN 
(
SELECT p.CID 
FROM diagnosis_opd o
LEFT JOIN person p
ON o.HOSPCODE=p.HOSPCODE and	 o.PID=p.PID 
WHERE substr(DIAGCODE,1,3) BETWEEN 'I05' AND 'I09' 
OR substr(DIAGCODE,1,3) IN ('I11','I13','I20','I52')
) b 
ON a.CID = b.CID  
SET a.GRP3 = '1';


# 4 Cerebrovascular Disease I60-I69
UPDATE me_need_flu a 
JOIN 
(
SELECT p.CID 
FROM diagnosis_opd o
LEFT JOIN person p
ON o.HOSPCODE=p.HOSPCODE and	 o.PID=p.PID 
WHERE substr(DIAGCODE,1,3) BETWEEN 'I60' AND 'I69' 
) b 
ON a.CID = b.CID  
SET a.GRP4 = '1';

# 5 Diabetes  DM BETWEEN 'E10' AND 'E14' 

UPDATE me_need_flu a 
JOIN 
(
SELECT p.CID 
FROM diagnosis_opd o
LEFT JOIN person p
ON o.HOSPCODE=p.HOSPCODE and	 o.PID=p.PID 
WHERE substr(DIAGCODE,1,3) BETWEEN 'E10' AND 'E14' 
) b 
ON a.CID = b.CID  
SET a.GRP5 = '1';




# 6 Chronic Renal Failure   BETWEEN 'N18' AND 'N19' 

UPDATE me_need_flu a 
JOIN 
(
SELECT p.CID 
FROM diagnosis_opd o
LEFT JOIN person p
ON o.HOSPCODE=p.HOSPCODE and	 o.PID=p.PID 
WHERE substr(DIAGCODE,1,3) BETWEEN 'N18' AND 'N19' 
) b 
ON a.CID = b.CID  
SET a.GRP6 = '1';


# 7 Cancer  Z511

UPDATE me_need_flu a 
JOIN 
(
SELECT p.CID 
FROM diagnosis_opd o
LEFT JOIN person p
ON o.HOSPCODE=p.HOSPCODE and	 o.PID=p.PID 
WHERE substr(DIAGCODE,1,4) ='Z511'
) b 
ON a.CID = b.CID  
SET a.GRP7 = '1';

# 8 Thaslassemia D56

UPDATE me_need_flu a 
JOIN 
(
SELECT p.CID 
FROM diagnosis_opd o
LEFT JOIN person p
ON o.HOSPCODE=p.HOSPCODE and	 o.PID=p.PID 
WHERE substr(DIAGCODE,1,3) ='D56'
) b 
ON a.CID = b.CID  
SET a.GRP8= '1';


# 9 SLE M32
UPDATE me_need_flu a 
JOIN 
(
SELECT p.CID 
FROM diagnosis_opd o
LEFT JOIN person p
ON o.HOSPCODE=p.HOSPCODE and	 o.PID=p.PID 
WHERE substr(DIAGCODE,1,3) ='M32'
) b 
ON a.CID = b.CID  
SET a.GRP9= '1';


# 10 HIV 'B20' and 'B24'
UPDATE me_need_flu a 
JOIN 
(
SELECT p.CID 
FROM diagnosis_opd o
LEFT JOIN person p
ON o.HOSPCODE=p.HOSPCODE and	 o.PID=p.PID 
WHERE substr(DIAGCODE,1,3) BETWEEN 'B20' and 'B24'
) b 
ON a.CID = b.CID  
SET a.GRP10= '1';


# 11 Pregnancy 
 
UPDATE me_need_flu a 
JOIN 
(
SELECT p.CID 
FROM diagnosis_opd o
LEFT JOIN person p
ON o.HOSPCODE=p.HOSPCODE and	 o.PID=p.PID 
WHERE substr(DIAGCODE,1,3) BETWEEN 'O00' and 'O99'
) b 
ON a.CID = b.CID  
SET a.GRP11= '1';

# 12 Mentaly and Congenital Abnormalities  
 
UPDATE me_need_flu a 
JOIN 
(
SELECT p.CID 
FROM diagnosis_opd o
LEFT JOIN person p
ON o.HOSPCODE=p.HOSPCODE and	 o.PID=p.PID 
WHERE substr(DIAGCODE,1,3) BETWEEN 'F70' and 'F79' OR substr(DIAGCODE,1,3) BETWEEN 'Q00' and 'Q99'
) b 
ON a.CID = b.CID  
SET a.GRP12= '1';

# C01 COPD

UPDATE me_need_flu a 
JOIN 
(
SELECT p.CID
,GROUP_CONCAT(c.CHRONIC ORDER BY DATE_DIAG DESC  SEPARATOR ',') as DX
FROM chronic c
LEFT JOIN person p
ON c.HOSPCODE=p.HOSPCODE and	 c.PID=p.PID 
WHERE substr(c.CHRONIC,1,3)  BETWEEN 'J41' AND 'J44' 
AND NOT ISNULL(p.CID) AND p.CID <>'' AND SUBSTR(p.CID,1,1)<>'0' AND SUBSTR(p.CID,1,1)<>'7' AND SUBSTR(p.CID,1,1)<>'8' AND SUBSTR(p.CID,1,1)<>'9'
GROUP BY p.CID	
) b 
ON a.CID = b.CID  
SET a.C01=b.DX;

# C02 Asthma J45-J46

UPDATE me_need_flu a 
JOIN 
(
SELECT p.CID
,GROUP_CONCAT(c.CHRONIC ORDER BY DATE_DIAG DESC  SEPARATOR ',') as DX
FROM chronic c
LEFT JOIN person p
ON c.HOSPCODE=p.HOSPCODE and	 c.PID=p.PID 
WHERE substr(c.CHRONIC,1,3)  BETWEEN 'J45' AND 'J46' 
AND NOT ISNULL(p.CID) AND p.CID <>'' AND SUBSTR(p.CID,1,1)<>'0' AND SUBSTR(p.CID,1,1)<>'7' AND SUBSTR(p.CID,1,1)<>'8' AND SUBSTR(p.CID,1,1)<>'9'
GROUP BY p.CID	
) b 
ON a.CID = b.CID  
SET a.C02=b.DX;


# C03 Heart Disease I05-I09 I11  I13  I20  I52  

UPDATE me_need_flu a 
JOIN 
(
SELECT p.CID
,GROUP_CONCAT(c.CHRONIC ORDER BY DATE_DIAG DESC  SEPARATOR ',') as DX
FROM chronic c
LEFT JOIN person p
ON c.HOSPCODE=p.HOSPCODE and	 c.PID=p.PID 
WHERE substr(c.CHRONIC,1,3)  BETWEEN  'I05' AND 'I09' 
OR substr(c.CHRONIC,1,3)  IN ('I11','I13','I20','I52')
AND NOT ISNULL(p.CID) AND p.CID <>'' AND SUBSTR(p.CID,1,1)<>'0' AND SUBSTR(p.CID,1,1)<>'7' AND SUBSTR(p.CID,1,1)<>'8' AND SUBSTR(p.CID,1,1)<>'9'
GROUP BY p.CID	
) b 
ON a.CID = b.CID  
SET a.C03=b.DX;


# C04 Cerebrovascular Disease I60-I69
UPDATE me_need_flu a 
JOIN 
(
SELECT p.CID
,GROUP_CONCAT(c.CHRONIC ORDER BY DATE_DIAG DESC  SEPARATOR ',') as DX
FROM chronic c
LEFT JOIN person p
ON c.HOSPCODE=p.HOSPCODE and	 c.PID=p.PID 
WHERE substr(c.CHRONIC,1,3) BETWEEN 'I60' and 'I69'
AND NOT ISNULL(p.CID) AND p.CID <>'' AND SUBSTR(p.CID,1,1)<>'0' AND SUBSTR(p.CID,1,1)<>'7' AND SUBSTR(p.CID,1,1)<>'8' AND SUBSTR(p.CID,1,1)<>'9'
GROUP BY p.CID	
) b 
ON a.CID = b.CID  
SET a.C04=b.DX;


#C05 Diabetes  DM BETWEEN 'E10' AND 'E14' 

UPDATE me_need_flu a 
JOIN 
(
SELECT p.CID
,GROUP_CONCAT(c.CHRONIC ORDER BY DATE_DIAG DESC  SEPARATOR ',') as DX
FROM chronic c
LEFT JOIN person p
ON c.HOSPCODE=p.HOSPCODE and	 c.PID=p.PID 
WHERE substr(c.CHRONIC,1,3) BETWEEN 'E10' AND 'E14' 
AND NOT ISNULL(p.CID) AND p.CID <>'' AND SUBSTR(p.CID,1,1)<>'0' AND SUBSTR(p.CID,1,1)<>'7' AND SUBSTR(p.CID,1,1)<>'8' AND SUBSTR(p.CID,1,1)<>'9'
GROUP BY p.CID	
) b 
ON a.CID = b.CID  
SET a.C05=b.DX;


# 6 Chronic Renal Failure   BETWEEN 'N18' AND 'N19' 

UPDATE me_need_flu a 
JOIN 
(
SELECT p.CID
,GROUP_CONCAT(c.CHRONIC ORDER BY DATE_DIAG DESC  SEPARATOR ',') as DX
FROM chronic c
LEFT JOIN person p
ON c.HOSPCODE=p.HOSPCODE and	 c.PID=p.PID 
WHERE substr(c.CHRONIC,1,3) BETWEEN  'N18' AND 'N19' 
AND NOT ISNULL(p.CID) AND p.CID <>'' AND SUBSTR(p.CID,1,1)<>'0' AND SUBSTR(p.CID,1,1)<>'7' AND SUBSTR(p.CID,1,1)<>'8' AND SUBSTR(p.CID,1,1)<>'9'
GROUP BY p.CID	
) b 
ON a.CID = b.CID  
SET a.C06=b.DX;

# 7 Cancer  Z511

UPDATE me_need_flu a 
JOIN 
(
SELECT p.CID
,GROUP_CONCAT(c.CHRONIC ORDER BY DATE_DIAG DESC  SEPARATOR ',') as DX
FROM chronic c
LEFT JOIN person p
ON c.HOSPCODE=p.HOSPCODE and	 c.PID=p.PID 
WHERE substr(c.CHRONIC,1,4) ='Z511'
AND NOT ISNULL(p.CID) AND p.CID <>'' AND SUBSTR(p.CID,1,1)<>'0' AND SUBSTR(p.CID,1,1)<>'7' AND SUBSTR(p.CID,1,1)<>'8' AND SUBSTR(p.CID,1,1)<>'9'
GROUP BY p.CID	
) b 
ON a.CID = b.CID  
SET a.C07=b.DX;

# 8 Thaslassemia D56

UPDATE me_need_flu a 
JOIN 
(
SELECT p.CID
,GROUP_CONCAT(c.CHRONIC ORDER BY DATE_DIAG DESC  SEPARATOR ',') as DX
FROM chronic c
LEFT JOIN person p
ON c.HOSPCODE=p.HOSPCODE and	 c.PID=p.PID 
WHERE substr(c.CHRONIC,1,3) ='D56'
AND NOT ISNULL(p.CID) AND p.CID <>'' AND SUBSTR(p.CID,1,1)<>'0' AND SUBSTR(p.CID,1,1)<>'7' AND SUBSTR(p.CID,1,1)<>'8' AND SUBSTR(p.CID,1,1)<>'9'
GROUP BY p.CID	
) b 
ON a.CID = b.CID  
SET a.C08=b.DX;


# 9 SLE M32

UPDATE me_need_flu a 
JOIN 
(
SELECT p.CID
,GROUP_CONCAT(c.CHRONIC ORDER BY DATE_DIAG DESC  SEPARATOR ',') as DX
FROM chronic c
LEFT JOIN person p
ON c.HOSPCODE=p.HOSPCODE and	 c.PID=p.PID 
WHERE substr(c.CHRONIC,1,3) ='M32'
AND NOT ISNULL(p.CID) AND p.CID <>'' AND SUBSTR(p.CID,1,1)<>'0' AND SUBSTR(p.CID,1,1)<>'7' AND SUBSTR(p.CID,1,1)<>'8' AND SUBSTR(p.CID,1,1)<>'9'
GROUP BY p.CID	
) b 
ON a.CID = b.CID  
SET a.C09=b.DX; 


# 10 HIV 'B20' and 'B24'

UPDATE me_need_flu a 
JOIN 
(
SELECT p.CID
,GROUP_CONCAT(c.CHRONIC ORDER BY DATE_DIAG DESC  SEPARATOR ',') as DX
FROM chronic c
LEFT JOIN person p
ON c.HOSPCODE=p.HOSPCODE and	 c.PID=p.PID 
WHERE substr(c.CHRONIC,1,3) BETWEEN   'B20' and 'B24'
AND NOT ISNULL(p.CID) AND p.CID <>'' AND SUBSTR(p.CID,1,1)<>'0' AND SUBSTR(p.CID,1,1)<>'7' AND SUBSTR(p.CID,1,1)<>'8' AND SUBSTR(p.CID,1,1)<>'9'
GROUP BY p.CID	
) b 
ON a.CID = b.CID  
SET a.C10=b.DX; 


##########################################################################################################################################
# summary

SELECT HOSPCODE,PID,CID,BIRTH
,TIMESTAMPDIFF(YEAR,BIRTH,'2017-06-01') as AGE
,GRP0,GRP1,GRP2,GRP3,GRP4,GRP5,GRP6,GRP7,GRP8,GRP9,GRP10,GRP11,GRP12
,C01,C02,C03,C04,C05,C06,C07,C08,C09,C10
,IFNULL(GRP1,0)+IFNULL(GRP2,0)+IFNULL(GRP3,0)+IFNULL(GRP4,0)+IFNULL(GRP5,0)+IFNULL(GRP6,0)
+IFNULL(GRP7,0)+IFNULL(GRP8,0)+IFNULL(GRP9,0)+IFNULL(GRP10,0)+IFNULL(GRP11,0)+IFNULL(GRP12,0)
+IF(NOT ISNULL(C01),1,0)
+IF(NOT ISNULL(C02),1,0)
+IF(NOT ISNULL(C03),1,0)
+IF(NOT ISNULL(C04),1,0)
+IF(NOT ISNULL(C05),1,0)
+IF(NOT ISNULL(C06),1,0)
+IF(NOT ISNULL(C07),1,0)
+IF(NOT ISNULL(C08),1,0)
+IF(NOT ISNULL(C09),1,0)
+IF(NOT ISNULL(C10),1,0)
 as RISKPOINT
FROM me_need_flu t
WHERE HOSPCODE='07714' 
AND TYPEAREA in ('1','3') 
AND DISCHARGE='9'
HAVING RISKPOINT > 0
ORDER BY RISKPOINT DESC ;

