SELECT p.HOSPCODE,p.PID,p.CID,p.`NAME`,p.LNAME,p.BIRTH,p.SEX,p.TYPEAREA,p.DISCHARGE 
,c.DATE_DIAG,c.CHRONIC,c.TYPEDISCH,c.DATE_DISCH
,n.DATE_SERV,n.BSTEST,n.BSLEVEL,n.SBP_1,n.SBP_2,n.DBP_1,n.DBP_2
FROM person p
LEFT JOIN chronic c
ON p.HOSPCODE=c.HOSPCODE AND p.PID=c.PID 
LEFT JOIN ncdscreen n
ON p.HOSPCODE=n.HOSPCODE AND p.PID=n.PID
