SELECT t.DIAGCODE,t.DIAGLAST,t.CHIEFCOMP,count(*) n  
FROM 
(

SELECT r.HOSPCODE,r.PID,r.SEQ,r.REFERID,r.HOSP_DESTINATION,r.DATETIME_SERV,r.CHIEFCOMP,r.PHYSICALEXAM,r.DIAGLAST
,s.DATE_SERV,s.CHIEFCOMP as CHIEFCOMPS ,s.REFEROUTHOSP 
,o.DIAGCODE,o.DIAGTYPE 
FROM diagnosis_opd o 

LEFT  JOIN service s
ON o.HOSPCODE=s.HOSPCODE AND o.PID=s.PID AND o.SEQ=s.SEQ   
LEFT  JOIN refer_history r
ON r.HOSPCODE=s.HOSPCODE AND r.PID=s.PID AND r.SEQ=s.SEQ 
WHERE r.HOSPCODE='07727' 
AND s.DATE_SERV  BETWEEN '2017-05-01' AND '2017-05-31'
) as t 
GROUP BY t.DIAGCODE,t.DIAGLAST
-- ,t.CHIEFCOMP
