SET @startdate='2015-10-01';
SET @stopdate='2016-09-30';

SELECT t1.HOSPCODE,t1.HOSPNAME,t1.TARGET
,t2.RESULT,ROUND((t2.RESULT*100/t1.TARGET),2) as PERCENT
,t3.FALSED
,t4.MISSED 
FROM 
(
SELECT HOSPCODE,HOSPNAME,count(*) TARGET 
FROM me_vaccined 
WHERE	  TYPEAREA in('1','3') AND DISCHARGE='9'
AND (BIRTH BETWEEN DATE_ADD(@startdate,INTERVAL -1 YEAR) AND DATE_ADD(@stopdate,INTERVAL -1 YEAR))
GROUP BY HOSPCODE
) as t1 
LEFT JOIN 
(
SELECT HOSPCODE,HOSPNAME,count(*) RESULT 
FROM me_vaccined 
WHERE	  TYPEAREA in('1','3') AND DISCHARGE='9'
AND (BIRTH BETWEEN DATE_ADD(@startdate,INTERVAL -1 YEAR) AND DATE_ADD(@stopdate,INTERVAL -1 YEAR))
AND NOT ISNULL(MMR_VISIT) AND MMR_VISIT <= DATE_ADD(BIRTH,INTERVAL 1 YEAR)
GROUP BY HOSPCODE 
) as t2
ON t1.HOSPCODE=t2.HOSPCODE 
LEFT JOIN 
(
SELECT HOSPCODE,HOSPNAME,count(*) AS FALSED 
FROM me_vaccined 
WHERE	  TYPEAREA in('1','3') AND DISCHARGE='9'
AND (BIRTH BETWEEN DATE_ADD(@startdate,INTERVAL -1 YEAR) AND DATE_ADD(@stopdate,INTERVAL -1 YEAR))
AND NOT ISNULL(MMR_VISIT) AND MMR_VISIT > DATE_ADD(BIRTH,INTERVAL 1 YEAR)
GROUP BY HOSPCODE 
) as t3
ON t1.HOSPCODE=t3.HOSPCODE 
LEFT JOIN 
(
SELECT HOSPCODE,HOSPNAME,count(*) AS MISSED 
FROM me_vaccined 
WHERE	  TYPEAREA in('1','3') AND DISCHARGE='9'
AND (BIRTH BETWEEN DATE_ADD(@startdate,INTERVAL -1 YEAR) AND DATE_ADD(@stopdate,INTERVAL -1 YEAR))
AND  ISNULL(MMR_VISIT) 
GROUP BY HOSPCODE 
) as t4
ON t1.HOSPCODE=t4.HOSPCODE 
