
SELECT person.HOSPCODE,person.PID,person.CID,person.BIRTH,person.TYPEAREA,person.DISCHARGE 
,t1.DATE_SERV
,t1.VACCINETYPE
,t1.VACCINEPLACE 
FROM person 
LEFT JOIN 
(
SELECT p.CID
,GROUP_CONCAT(e.DATE_SERV ORDER BY e.DATE_SERV) as DATE_SERV
,GROUP_CONCAT(e.VACCINETYPE ORDER BY e.DATE_SERV) as VACCINETYPE
,GROUP_CONCAT(e.VACCINEPLACE ORDER BY e.DATE_SERV) as VACCINEPLACE 
FROM epi e
INNER JOIN person p
ON e.HOSPCODE=p.HOSPCODE AND e.PID=p.PID 
WHERE e.VACCINETYPE in ('061','071','072','073','074')
GROUP BY  p.CID
) as t1 
ON person.CID=t1.CID
WHERE TIMESTAMPDIFF(MONTH,person.birth,'2018-11-01') BETWEEN 13 AND 144 
AND person.HOSPCODE='09248'
GROUP BY person.CID  
