SELECT t1.HOSPCODE
,t1.CID
,t1.PID
,t1.NAME
,t1.LNAME
,t1.BIRTH
,t2.house
,t2.village,t2.tambon,t2.ampur,t2.changwat
,t3.measle1,t3.measle2,t3.measle3
,CASE WHEN (t3.measle1=t3.measle2 OR ISNULL(t3.measle2)) THEN 'needs'
			WHEN t3.measle1<t3.measle2 THEN 'fully'
			ELSE NULL 
END as 'books'

FROM  person t1
LEFT JOIN home t2
ON t1.HOSPCODE=t2.HOSPCODE AND t1.HID=t2.HID
LEFT JOIN 
(
SELECT t9.X AS CID 
,DATE_FORMAT(SPLIT_STR(GROUP_CONCAT(t9.DATE_SERV ORDER BY t9.DATE_SERV SEPARATOR ',') ,',',1),"%Y-%m-%d") as measle1
,DATE_FORMAT(SPLIT_STR(GROUP_CONCAT(t9.DATE_SERV ORDER BY t9.DATE_SERV SEPARATOR ',') ,',',2),"%Y-%m-%d") as measle2
,DATE_FORMAT(SPLIT_STR(GROUP_CONCAT(t9.DATE_SERV ORDER BY t9.DATE_SERV SEPARATOR ',') ,',',3),"%Y-%m-%d") as measle3
FROM 
(
SELECT DISTINCT IF(ISNULL(t.CID),t.IDCARD,t.CID) as X
,t.VACCINETYPE
,t.DATE_SERV
FROM 
( 
SELECT  p.CID,e.CID as IDCARD
,e.VACCINETYPE
,e.DATE_SERV
FROM epi e
LEFT JOIN  person p 
ON e.hospcode=p.hospcode AND e.pid=p.pid

WHERE VACCINETYPE in ('061','071','072','073','074','075','076')
UNION 
(
SELECT cid as CID,'' as IDCARD,'061' as  VACCINETYPE,visitdate as DATE_SERV
FROM mmr1
) 
UNION 
(
SELECT cid as CID,'' as IDCARD,'073' as  VACCINETYPE,visitdate as DATE_SERV
FROM mmr2
) 
) as ta
) as t9
GROUP BY CID
) as t3
ON t1.CID=t3.CID


WHERE t1.TYPEAREA in ('1','3')
AND t1.DISCHARGE='9'
AND TIMESTAMPDIFF(MONTH,t1.birth,'2018-11-01') BETWEEN 13 AND 144 
AND t1.HOSPCODE='09248'
-- AND t1.CID='1849902013148'
HAVING books='needs'
